# Generated by Django 2.1 on 2020-03-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.CharField(max_length=15, unique=True)),
                ('charging_fee', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('occupied', 'occupied'), ('inactive', 'inactive'), ('free', 'free')], max_length=20)),
            ],
            options={
                'verbose_name': 'charging_point',
                'verbose_name_plural': 'charging_points',
            },
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sample Name', max_length=50, null=True, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
                ('parking_fee', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'charging_station',
                'verbose_name_plural': 'charging_stations',
            },
        ),
        migrations.AddIndex(
            model_name='chargingstation',
            index=models.Index(fields=['name'], name='charging_st_name_9ebb5a_idx'),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='charging_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='charging_point', to='charging_stations.ChargingStation'),
        ),
        migrations.AddIndex(
            model_name='chargingpoint',
            index=models.Index(fields=['port_number'], name='charging_st_port_nu_bd62ae_idx'),
        ),
    ]
